MovieTicket/MovieTicket/Models/Phim.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieTicket.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Phim
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Phim()
        {
            this.SuatChieu = new HashSet<SuatChieu>();
        }

        [Required(ErrorMessage = "Không được để trống trường này")]
        [DisplayName("Mã phim")]
        public int maphim { get; set; }

        [Required(ErrorMessage = "Không được để trống trường này")]
        [DisplayName("Mã thể loại")]
        public int matheloai { get; set; }

        [Required(ErrorMessage = "Không được để trống trường này")]
        [DisplayName("Đạo diễn")]
        public string daodien { get; set; }

        [Required(ErrorMessage = "Không được để trống trường này")]
        [DisplayName("Tên phim")]
        public string tenphim { get; set; }

        [Required(ErrorMessage = "Không được để trống trường này")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [DisplayName("Ngày khởi chiếu")]
        public System.DateTime ngaykhoichieu { get; set; }

        [Required(ErrorMessage = "Không được để trống trường này")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [DisplayName("Ngày kết thúc")]
        public System.DateTime ngayketthuc { get; set; }

        [Required(ErrorMessage = "Không được để trống trường này")]
        [DisplayName("Mô tả")]
        public string mota { get; set; }

        [Required(ErrorMessage = "Không được để trống trường này")]
        [DisplayName("Hình")]
        public string hinh { get; set; }

        [Required(ErrorMessage = "Không được để trống trường này")]
        [DisplayName("Nhà sản xuất")]
        public string nhasanxuat { get; set; }

        [DataType(DataType.Duration)]
        [Required(ErrorMessage = "Không được để trống trường này")]
        [DisplayName("Thời lượng")]
        public int thoiluong { get; set; }

        [DataType(DataType.Url)]
        [Required(ErrorMessage = "Không được để trống trường này")]
        [DisplayName("Trailer")]
        public string trailer { get; set; }

        [DisplayName("Thể loại")]
        public virtual TheLoai TheLoai { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SuatChieu> SuatChieu { get; set; }
    }
}

MovieTicket/MovieTicket/Areas/Admin/Controllers/PhimsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MovieTicket.Models;
using PagedList;
using System.Collections;
using System.Data.SqlClient;
using System.Data.Entity.Core;

namespace MovieTicket.Areas.Admin.Controllers
{
    [Authorize(Roles ="ql")]
    public class PhimsController : Controller
    {
        private qldvEntities2 db = new qldvEntities2();

        // GET: Admin/Phims
        //public ActionResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        //{
        //    ViewBag.CurrentSort = sortOrder;

        //    ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
        //    ViewBag.DateSortParm = sortOrder == "Date" ? "date_desc" : "Date";

        //    if (searchString != null)
        //    {
        //        page = 1;
        //    }
        //    else
        //    {
        //        searchString = currentFilter;
        //    }
        //    ViewBag.CurrentFilter = searchString;
        //    //search
        //    var phims = from s in db.Phims.Include(p => p.TheLoai)
        //                   select s;
        //    if (!String.IsNullOrEmpty(searchString))
        //    {
        //        phims = phims.Where(s => s.tenphim.Contains(searchString));
        //    }
        //    //sort
        //    switch (sortOrder)
        //    {
        //        case "name_desc":
        //            phims = phims.OrderByDescending(s => s.tenphim);
        //            break;
        //        case "Date":
        //            phims = phims.OrderBy(s => s.ngaykhoichieu);
        //            break;
        //        case "date_desc":
        //            phims = phims.OrderByDescending(s => s.ngaykhoichieu);
        //            break;
        //        default:
        //            phims = phims.OrderBy(s => s.tenphim);
        //            break;
        //    }

        //    int pageSize = 5;
        //    int pageNumber = (page ?? 1);
        //    return View(phims.ToPagedList(pageNumber, pageSize));
        //}
        public ActionResult Index(string searchString)
        {
            if (!String.IsNullOrEmpty(searchString))
            {
                return View(db.Database.SqlQuery<Phim>("exec sp_loadPhimTheoTen {0}", searchString).ToList());
            }
            return View(db.Database.SqlQuery<Phim>("exec sp_loadTatCaPhim").ToList());
        }

        // GET: Admin/Phims/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Phim phim = db.Database.SqlQuery<Phim>("exec sp_loadChiTietPhim {0}", id).First<Phim>();
            if (phim == null)
            {
                return HttpNotFound();
            }
            return View(phim);
        }

        // GET: Admin/Phims/Create
        public ActionResult Create()
        {
            ViewBag.matheloai = new SelectList(db.TheLoai, "matheloai", "tentheloai");
            return View();
        }

        // POST: Admin/Phims/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "maphim,matheloai,daodien,tenphim,ngaykhoichieu,ngayketthuc,mota,hinh,nhasanxuat,thoiluong,trailer")] Phim phim)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    //db.Phims.Add(phim);
                    db.Database.SqlQuery<Phim>
                        ("exec sp_addPhim {0},{1},{2},{3},{4},{5},{6},{7},{8},{9}", 
                        phim.matheloai.ToString(), phim.daodien.ToString(), phim.tenphim.ToString(), 
                        phim.ngaykhoichieu, phim.ngayketthuc, phim.mota.ToString(), 
                        phim.hinh.ToString(), phim.nhasanxuat.ToString(), phim.thoiluong.ToString(), 
                        phim.trailer.ToString()).ToList();
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch (EntityCommandExecutionException ex)
            {
                return RedirectToAction("Index");
            }


            ViewBag.matheloai = new SelectList(db.TheLoai, "matheloai", "tentheloai", phim.matheloai);
            return View(phim);
        }

        // GET: Admin/Phims/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Phim phim = db.Database.SqlQuery<Phim>("exec sp_loadChiTietPhim {0}", id).First<Phim>();
            if (phim == null)
            {
                return HttpNotFound();
            }
            ViewBag.matheloai = new SelectList(db.TheLoai, "matheloai", "tentheloai", phim.matheloai);
            return View(phim);
        }

        // POST: Admin/Phims/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "maphim,matheloai,daodien,tenphim,ngaykhoichieu,ngayketthuc,mota,hinh,nhasanxuat,thoiluong,trailer")] Phim phim)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    //db.Phims.Add(phim);
                    db.Database.SqlQuery<Phim>
                        ("exec sp_editPhim {0},{1},{2},{3},{4},{5},{6},{7},{8},{9},{10}", phim.maphim.ToString(),
                        phim.matheloai.ToString(), phim.daodien.ToString(), phim.tenphim.ToString(),
                        phim.ngaykhoichieu, phim.ngayketthuc, phim.mota.ToString(),
                        phim.hinh.ToString(), phim.nhasanxuat.ToString(), 
                        phim.thoiluong.ToString(), phim.trailer.ToString()).ToList();
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {
                
                return RedirectToAction("Index");

            }
            ViewBag.matheloai = new SelectList(db.TheLoai, "matheloai", "tentheloai", phim.matheloai);
            return View(phim);
        }

        // GET: Admin/Phims/Delete/5
        //public ActionResult Delete(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Phim phim = db.Phims.Find(id);
        //    if (phim == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(phim);
        //}

        //// POST: Admin/Phims/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public ActionResult DeleteConfirmed(int id)
        //{
        //    Phim phim = db.Phims.Find(id);
        //    db.Phims.Remove(phim);
        //    db.SaveChanges();
        //    return RedirectToAction("Index");
        //}

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        
    }
}
    

MovieTicket/MovieTicket/Areas/Admin/Views/Phims/Create.cshtml
@model MovieTicket.Models.Phim

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
<h2>Create</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Phim</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @*<div class="form-group">
            @Html.LabelFor(model => model.maphim, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.maphim, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.maphim, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.matheloai, "Thể loại", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("matheloai", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.matheloai, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.daodien, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.daodien, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.daodien, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.tenphim, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.tenphim, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.tenphim, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ngaykhoichieu, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ngaykhoichieu, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ngaykhoichieu, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ngayketthuc, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ngayketthuc, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ngayketthuc, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.mota, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.mota, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.mota, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.hinh, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.hinh, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.hinh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.nhasanxuat, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nhasanxuat, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nhasanxuat, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.thoiluong, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.thoiluong, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.thoiluong, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.trailer, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.trailer, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.trailer, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink(" Trở về danh sách", "Index", "", htmlAttributes: new { @class = "fa fa-arrow-circle-left create" })
</div>

MovieTicket/MovieTicket/Areas/Admin/Views/Phims/Delete.cshtml
@model MovieTicket.Models.Phim

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
<div class="validation-system">
    <div class="validation-form">
        <h2>Delete</h2>

        <h3>Are you sure you want to delete this?</h3>
        <div>
            <h4>Phim</h4>
            <hr />
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.daodien)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.daodien)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.tenphim)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.tenphim)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.ngaykhoichieu)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.ngaykhoichieu)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.ngayketthuc)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.ngayketthuc)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.mota)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.mota)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.hinh)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.hinh)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.nhasanxuat)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.nhasanxuat)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.thoiluong)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.thoiluong)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.trailer)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.trailer)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.TheLoai.tentheloai)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.TheLoai.tentheloai)
                </dd>

            </dl>

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-actions no-color">
                    <input type="submit" value="Delete" class="btn btn-default" /> |
                    @Html.ActionLink("Back to List", "Index")
                </div>
            }
        </div>
    </div>
</div>

MovieTicket/MovieTicket/Areas/Admin/Views/Phims/Details.cshtml
@model MovieTicket.Models.Phim

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
<div class="validation-system">
    <div class="validation-form">
        <h2>Details</h2>

        <div>
            <h4>Phim</h4>
            <hr />
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.daodien)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.daodien)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.tenphim)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.tenphim)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.ngaykhoichieu)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.ngaykhoichieu)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.ngayketthuc)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.ngayketthuc)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.mota)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.mota)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.hinh)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.hinh)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.nhasanxuat)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.nhasanxuat)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.thoiluong)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.thoiluong)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.trailer)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.trailer)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.TheLoai.tentheloai)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.TheLoai.tentheloai)
                </dd>

            </dl>
        </div>
        <p>
            @Html.ActionLink(" Trở về danh sách", "Index", "", htmlAttributes: new { @class = "fa fa-arrow-circle-left create" })
            @Html.ActionLink(" Chỉnh sửa", "Edit", new { id = Model.maphim }, htmlAttributes: new { @class = "fa fa-pencil-square-o create" })
            
        </p>
    </div>
</div>

MovieTicket/MovieTicket/Areas/Admin/Views/Phims/Index.cshtml
@model IEnumerable<MovieTicket.Models.Phim>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
<h2>Index</h2>
<form class="navbar-left-right">
    @using (Html.BeginForm("Index", "Phims", FormMethod.Get))
    {
        <p>
            <!--@Html.TextBox("SearchString", ViewBag.CurrentFilter as string)-->
            @Html.TextBox("SearchString", "Tìm theo tên phim", ViewBag.CurrentFilter as string, new {  @autocomplete = "off", @value = "Tìm theo tên phim", @onfocus = "this.value = '';", @onblur = "if (this.value == '') {this.value = 'Tìm theo tên phim';}" })
            <input type="submit" value="" class="fa fa-search">
        </p>
    }
</form>
        @*<input type="text" value="Search..." onfocus="this.value='';" onblur="if (this.value == '') {this.value = 'Search...';}" />
        <input type="submit" value="" class="fa fa-search">*@
    
<br/>
<br/>
<p>
    @Html.ActionLink(" Thêm phim", "Create", "", htmlAttributes: new { @class = "fa fa-plus-circle create" })
</p>
<table class="table" style="table-layout: fixed; width:100%">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.daodien)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.tenphim)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ngaykhoichieu)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ngayketthuc)
        </th>
        @*<th>
            Mô tả
        </th>*@
        <th>
            @Html.DisplayNameFor(model => model.hinh)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.nhasanxuat)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.thoiluong)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.trailer)
        </th>
        @*<th>
            Tên thể loại
        </th>*@
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.daodien)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.tenphim)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ngaykhoichieu.Day)-@Html.DisplayFor(modelItem => item.ngaykhoichieu.Month)-@Html.DisplayFor(modelItem => item.ngaykhoichieu.Year)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ngayketthuc.Day)-@Html.DisplayFor(modelItem => item.ngayketthuc.Month)-@Html.DisplayFor(modelItem => item.ngayketthuc.Year)
            </td>
            @*<td>
                @Html.DisplayFor(modelItem => item.mota)
            </td>*@
            <td style="word-wrap:break-word">
                @Html.DisplayFor(modelItem => item.hinh)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.nhasanxuat)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.thoiluong)
            </td>
            <td style="word-wrap:break-word">
                @Html.DisplayFor(modelItem => item.trailer)
            </td>
            @*<td>
                @Html.DisplayFor(modelItem => item.TheLoai.tentheloai)
            </td>*@
            <td>
                @Html.ActionLink(" ", "Edit", new { id = item.maphim }, new { @class = "fa fa-edit option" }) | 
                @Html.ActionLink(" ", "Details", new { id = item.maphim }, new { @class = "fa fa-info-circle option" }) @*|
                @Html.ActionLink("Delete", "Delete", new { id = item.maphim })*@
            </td>
        </tr>
    }

</table>